name: base
channels:
  - jfear
  - dranew
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  #- bcftools>=1.10
  - pyyaml
  - xlsxwriter
  - python>=3.8
  - snakemake>=6.6
  - bcl2fastq=2.19
  - fastqc>=0.11
  - cutadapt=3.4
  #- bwa=0.7.17
  #- bowtie2=2.4
  - samtools>=1.10
  - mosdepth>=0.3.1
  #- gatk4=4.2.0.0
  #- picard>=2.5
  - numpy>=1.10
  - pandas>=1.2
  - matplotlib
  - bedtools>=2.26
  - tabix
  #- snpeff=5.0
  #- snpsift=4.3
  - pip
  - statsmodels>=0.12
