#---- Config files ----
"conda_config": "workflow/envs/conda.yaml"
#----
#---- Directory structure config ----

#---- Resources ----
#-------- References --------
#-------- Variant filtration ---------
#-------- Annotation --------

#---- Input ----
"input_dir": "input/"

#"pacbio_subdir": "pacbio/"
#"nanopore_subdir": "nanopore/"
#"bionano_subdir": "bionano/"
#"hic_subdir": "hic/"
#"lr_subdir": "lr/"

#----

#----
#---- Output directory and subdirectories ----
"out_dir": "results"
#--------- Subdirectories --------
"first_level_subdir_list":
  - "config"
  - "data"
  - "qc"
  - "log"
  - "benchmark"
  - "cluster_log"
  - "cluster_error"
  - "preprocessing"
  - "basecall"
  - "kmer"
  - "contig"
  - "purge_dups"
  - "lr_scaffolding"
  - "bionano_scaffolding"
  - "hic_scaffolding"

"config_subdir": "config"
"data_subdir": "data"
"qc_subdir": "qc"
"kmer_subdir": "kmer"
"log_subdir": "logs"

"benchmark_subdir": "benchmarks"
"cluster_log_subdir": "cluster_logs"
"cluster_error_subdir": "cluster_errors"
"preprocessing_subdir": "preprocessing"
"basecall_subdir": "basecall"
"contig_subdir": "contig"
"purge_dups_subdir": "purge_dups"
"lr_scaffolding_subdir": "lr_scaffolding"
"bionano_scaffolding_subdir": "bionano_scaffolding"
"hic_scaffolding_subdir": "hic_scaffolding"


"fastqc_subdir": "fastqc"
"multiqc_subdir": "multiqc"

#--------

#---- Tool parameters ----
"parameters":
    "default":
        "threads":
            "create_fastq_links": 1
            "fastqc": 1
            "multiqc": 1
            "cutadapt": 5
            "jellyfish": 30
            "meryl": 30
            "genomescope": 1
            "parse_genomescope_output": 1
            "hifiasm": 30
            "gfa2fasta": 1


            ref_faidx: 1
            ref_dict: 1
            bwa_index: 1
            merge_raw_fastq: 1

            bwa: 25
            bowtie2: 8
            sort: 2
            fixmate: 1
            index: 1
            mosdepth: 3
            basecall: 30
            get_basecall_stats: 1
            picard: 1
        "memory_mb":
            "create_fastq_links": 100
            "fastqc": 5000
            "multiqc": 1000
            "cutadapt": 10000
            "jellyfish": 200000
            "genomescope": 300
            "parse_genomescope_output": 100
            "hifiasm": 50000
            "gfa2fasta": 10000

            ref_faidx: 1000
            ref_dict: 1000
            bwa_index: 10000
            fastqc_per_lane_raw: 8000
            merge_raw_fastq: 2000
            fastqc_merged_raw: 2000

            fastqc_filtered: 2000
            index: 10000
            bwa: 10000
            bowtie2: 10000
            fixmate: 10000
            mosdepth: 4000 #The amount of memory is approximately equal to 32-bits * longest chrom length, so for the 249MB chromosome 1, it will require 1GB of memory.
            basecall: 20000
        "time":
            "create_fastq_links": "00:05:00"
            "fastqc": "04:00:00"
            "multiqc": "00:10:00"
            "cutadapt": "04:00:00"
            "jellyfish": "08:00:00"
            "meryl": "08:00:00"
            "genomescope": "01:00:00"
            "parse_genomescope_output": "00:10:00"
            "hifiasm": "08:00:00"
            "gfa2fasta": "08:00:00"

            index: "10:00:00"
            bwa_map: "05:00:00"
            bowtie2_rna_map: "05:00:00"
            mosdepth: "02:00:00"
            basecall: "10:00:00"

            bowtie2_index: "12:00:00"

            get_basecall_stats: "00:10:00"
            gather_per_library_read_stats: "00:10:00"

            rmdup_raw_reads: "04:00:00"
            merge_target_regions_raw_reads: "00:10:00"
            merge_all_annotation: "00:10:00"

            merge_rna_counts_by_replicates: "00:30:00"

        "tool_options":
            "cutadapt":
                "pacbio":
                    "error_rate": 0.1 # --error-rate / -e
                    "min_adapter_length": 35 # --overlap / -O
                    "adapter_match_times": 3 # -n / --times
                    "check_read_rc": True # --rc
                    "discard_trimmed": True # --discard-trimmed / --discard
                    "anywhere_adapter_list": # -b, multiple times
                        - "ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT"
                        - "ATCTCTCTCTTTTCCTCCTCCTCCGTTGTTGTTGTTGAGAGAGAT"
            "fastqc":
                "kmer_length": 7
            "mosdepth":
                "min_mapping_quality": 10
            "jellyfish":
                "min_coverage": 1
                "max_coverage": 100000000
                "increment": 1
                "pacbio":
                    "kmer_length":
                        - 21
                    "hash_size": "20G"
                    "min_coverage": 1
                    "max_coverage": 100000000
                    "increment": 1
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "20G"
                    "min_coverage": 1
                    "max_coverage": 100000000
                    "increment": 1
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21
            "hifiasm":
                "purge level": 0 # -l purge level. 0: no purging; 1: light; 2/3: aggressive [0 for trio; 3 for unzip]
                "cov_multiplicator": 4.5 # 4.5 *lambda
    "micro": # < 15 Mbp, yeasts and bacteria
        "threads":
            "jellyfish": 30
            "hifiasm": 30
        "memory_mb":
            "jellyfish": 2000
            "meryl": 2000
            "hifiasm": 10000 # needs adjustment, very approximate value
        "time":
            "jellyfish": "01:00:00"
            "hifiasm": "02:00:00"
        "tool_options":
            "jellyfish":
                "pacbio":
                    "kmer_length":
                        - 1
                    "hash_size": "200M"
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "200M"
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21
    "mini": # < 150 Mbp, fungi, Arabidopsis thaliana and Caenorabditis elegans
        "threads":
            "jellyfish": 30
            "hifiasm": 30
        "memory_mb":
            "jellyfish": 20000
            "meryl": 20000
            "hifiasm": 20000
        "time":
            "jellyfish": "02:00:00"
            "hifiasm": "04:00:00"
        "tool_options":
            "jellyfish":
                "pacbio":
                    "kmer_length":
                        - 21
                    "hash_size": "2G"
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "2G"
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21
    "small": # < 500 Mbp, drosophilla, tetraodon
        "threads":
            "jellyfish": 30
            "hifiasm": 30
        "memory_mb":
            "jellyfish": 60000
            "meryl": 60000
            "hifiasm": 40000
        "time":
            "jellyfish": "04:00:00"
            "hifiasm": "08:00:00"
        "tool_options":
            "jellyfish":
                "pacbio":
                    "kmer_length":
                        - 21
                    "hash_size": "7G"
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "7G"
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21
    "normal": # < 1500 Mbp, most of birds
        "threads":
            "jellyfish": 30
            "hifiasm": 30
        "memory_mb":
            "jellyfish": 200000
            "hifiasm": 80000
            "meryl": 80000
        "time":
            "jellyfish": "08:00:00"
            "hifiasm": "12:00:00"
        "tool_options":
            "jellyfish":
                "pacbio":
                    "kmer_length":
                        - 21
                    "hash_size": "20G"
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "20G"
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21
    "big": # < 2500 Mbp, most of mammals
        "threads":
            "jellyfish": 30
            "hifiasm": 30
        "memory_mb":
            "jellyfish": 300000
            "hifiasm": 150000
            "meryl": 300000
        "time":
            "jellyfish": "12:00:00"
            "hifiasm": "16:00:00"
        "tool_options":
            "jellyfish":
                "pacbio":
                    "kmer_length":
                        - 21
                    "hash_size": "32G"
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "32G"
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21
    "large": # < 5000 Mbp, human
        "threads":
            "jellyfish": 30
            "hifiasm": 30
        "memory_mb":
            "jellyfish": 600000
            "meryl": 300000
            "hifiasm": 300000
        "time":
            "jellyfish": "24:00:00"
            "hifiasm": "24:00:00"
        "tool_options":
            "jellyfish":
                "pacbio":
                    "kmer_length":
                        - 21
                    "hash_size": "64G"
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "64G"
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21
    "giant": # < 15000 Mbp, big plant genomes
        "threads":
            "jellyfish": 30
            "hifiasm": 30
        "memory_mb":
            "jellyfish": 1100000
            "meryl": 300000
            "hifiasm": 1000000
        "time":
            "jellyfish": "48:00:00"
            "hifiasm": "48:00:00"
        "tool_options":
            "jellyfish":
                "pacbio":
                    "kmer_length":
                        - 21
                    "hash_size": "128G"
                "illumina":
                    "kmer_length":
                        - 21
                    "hash_size": "128G"
            "meryl":
                "pacbio":
                    "kmer_length":
                        - 21
                "illumina":
                    "kmer_length":
                        - 21

"kmer_counter_list":
    - "jellyfish"
    - "meryl" #TODO: test

"allowed_data_types":
    - "pacbio"
    - "nanopore"
    - "bionano"
    - "hic"
    - "lr"

"long_read_data":
    - "pacbio"
    - "nanopore"

"genome_size_estimation_data":
    - "pacbio"


"fastq_based_data":
    - "pacbio"
    - "nanopore"
    - "hic"
    - "lr"

"paired_fastq_based_data":
    - "hic"
    - "lr"

"fastq_extension": ".fastq.gz"
"cmap_extension": ".cmap"

"ploidy": 2
"genome_name": "genome"
#---- Pipeline modes ----

"starting_point": "fastq" # "bcl2"
"data_types": "pacbio_hic" # TODO: add "pacbio_bionano_hic", "pacbio_lr_bionano_hic", "pacbio_lr_hic"  and "pacbio"

"mode": "full" # Allowed modes: "check_input", "qc", "filtering"
# TODO:  add modes:  "create_map_bionano", "contig", "scaffold_bionano", "scaffold_hic"
# Possible additional modes:
# add "basecall", "basecall_pacbio", "basecall_hic", "basecall_lr", basecall_stlfr

"parameter_set": "default"